<?php

return [
    'admin_columns' => [
        ['data'=>'id' , 'name' => 'Id'],
        ['data'=>'date' , 'name' => 'Date'],
        ['data'=>'meal_type' , 'name' => 'Meal Type'],
        ['data'=>'contacts_name' , 'name' => 'Name'],
        ['data'=>'address' , 'name' => 'Address'],
        ['data'=>'postal' , 'name' => 'Postal Code'],
        ['data'=>'pax' , 'name' => 'Pax'],
        ['data'=>'addon' , 'name' => 'Addon'],
        ['data'=>'remark' , 'name' => 'Remark'],
        ['data'=>'delivery_note' , 'name' => 'Delivery Note'],
        ['data'=>'hp_number' , 'name' => 'Hp Number'],
        ['data'=>'driver_name' , 'name' => 'Driver Name'],
    ],
    'saif_columns' => [
        ['data'=>'id' , 'name' => 'Id'],
        ['data'=>'date' , 'name' => 'Date'],
        ['data'=>'meal_type' , 'name' => 'Meal Type'],
        ['data'=>'contacts_name' , 'name' => 'Name'],
        ['data'=>'pax' , 'name' => 'Pax'],
        ['data'=>'addon' , 'name' => 'Addon'],
    ],
    'user_columns' => [
        ['data'=>'id' , 'name' => 'Id'],
        ['data'=>'date' , 'name' => 'Date'],
        ['data'=>'meal_type' , 'name' => 'Meal Type'],
        ['data'=>'type' , 'name' => 'Unit Name'],
        ['data'=>'contacts_name' , 'name' => 'Name'],
        ['data'=>'pax' , 'name' => 'Pax'],
        ['data'=>'addon' , 'name' => 'Addon'],
        ['data'=>'address' , 'name' => 'Address'],
        ['data'=>'postal' , 'name' => 'Postal Code'],
        ['data'=>'cancel_reason' , 'name' => 'Cancel Reason'],
        ['data'=>'compensate' , 'name' => 'Compensate'],
        ['data'=>'action' , 'name' => 'Action'],
    ],
    'sell_columns' => [
        ['data'=>'id' , 'name' => 'Id'],
        ['data'=>'date' , 'name' => 'Date'],
        ['data'=>'meal_type' , 'name' => 'Meal Type'],
        ['data'=>'contacts_name' , 'name' => 'Name',],
        ['data'=>'pax' , 'name' => 'Pax'],
        ['data'=>'addon' , 'name' => 'Addon'],
        ['data'=>'address' , 'name' => 'Address'],
        ['data'=>'postal' , 'name' => 'Postal Code'],
        ['data'=>'cancel_reason' , 'name' => 'cancel_reason'],
        ['data'=>'compensate' , 'name' => 'compensate'],
    ],

    'product_type' => [
        0 => 'Not Applicable',
        1 => 'Lunch',
        2 => 'Dinner',
        3 => 'Both',
    ],

    'user_status' => [
        \App\Utils\AppConstant::FINAL,
        \App\Utils\AppConstant::PROCESSING,
        \App\Utils\AppConstant::COMPLETED,
        \App\Utils\AppConstant::CANCELLED,
        \App\Utils\AppConstant::PAYMENT_PENDING,
        \App\Utils\AppConstant::REFUND,
        \App\Utils\AppConstant::FAILED,
    ],
    'admin_status' => [
        \App\Utils\AppConstant::FINAL,
        \App\Utils\AppConstant::PROCESSING,
        \App\Utils\AppConstant::COMPLETED,
        \App\Utils\AppConstant::CANCELLED,
        \App\Utils\AppConstant::PAYMENT_PENDING,
        \App\Utils\AppConstant::REFUND,
        \App\Utils\AppConstant::FAILED,
    ],
    'saif_status' => [
        \App\Utils\AppConstant::FINAL,
        \App\Utils\AppConstant::COMPLETED,
    ],

];
